version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    networks:
      - server_database_network
 
  mongosh:
    image: mongodb/mongodb-community-server:latest
    container_name: mongosh
    entrypoint: mongosh
    command: "mongodb://mongodb:27017/"
    depends_on:
      - mongodb
    networks:
      - server_database_network

volumes:
  data:

networks:
  server_database_network:
    external: true

